steps:
- name: gcr.io/google.com/cloudsdktool/cloud-sdk:latest
  entrypoint: bash
  args: 
    - build.sh
  secretEnv: ['OAUTH_TOKEN']

availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/oauth_token/versions/latest
    env: 'OAUTH_TOKEN'
  
timeout: 24h